name: Build index

on:
    workflow_dispatch:
    push:
      branches:
        - extensions
      paths:
        - 'extensions/**.json'
        - 'tags.json'
        - 'index.json'

permissions:
    contents: write

jobs:
    build-extension-index-jobs:
        runs-on: ubuntu-latest
        if: github.event.repository.fork == false
        steps:
        - name: Checkout extensions
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
            ref: 'extensions'
            path: extensions

        - name: Checkout master
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
            ref: 'master'
            path: master

        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Build extension index
          run: python extensions/build_index.py

        - name: Validate index - extension
          run: python extensions/validate_json.py

        - name: Validate index - master
          run: python extensions/validate_json.py

        - name: Get last commit message - extensions
          id: last-commit-message-extensions
          run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

        - name: Get last commit message - master
          id: last-commit-message-master
          run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

        - name: Commit - extensions
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: ${{ steps.last-commit-message-extensions.outputs.msg }}
            commit_options: '--amend --no-edit'
            file_pattern: '*.json'
            push_options: '--force'
            skip_fetch: true
            repository: extensions

        - name: Commit - master
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: ${{ steps.last-commit-message-master.outputs.msg }}
            commit_options: '--amend --no-edit'
            file_pattern: '*.json'
            push_options: '--force'
            skip_fetch: true
            repository: master